# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b3421d95c95d869187888322a123642a0dbc1beb70c4f62602d260ec6ce7945e10d6b7b3826f7f30bbe2fb8f78413def90ad9c539f8d7404db21c6a59918d37

test:
  secret_key_base: 5cb5cd86a296c7dad60d3d024d2dd33eb5c7544e91192ebfef2214fa04873030749e87c35e7f26e128284f29d1fdbc9bb4de832c5a3cee40bad3b27d8e8096a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>